// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTicker(arg1) {
  return window['go']['app']['App']['AddTicker'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['app']['App']['GetSetting'](arg1);
}

export function GetWatchlist() {
  return window['go']['app']['App']['GetWatchlist']();
}

export function RemoveTicker(arg1) {
  return window['go']['app']['App']['RemoveTicker'](arg1);
}

export function ReorderWatchlist(arg1) {
  return window['go']['app']['App']['ReorderWatchlist'](arg1);
}

export function SearchTickers(arg1) {
  return window['go']['app']['App']['SearchTickers'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['app']['App']['SetSetting'](arg1, arg2);
}

export function ValidateTicker(arg1) {
  return window['go']['app']['App']['ValidateTicker'](arg1);
}
