// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTicker(arg1:string):Promise<void>;

export function GetSetting(arg1:string):Promise<string>;

export function GetWatchlist():Promise<Array<{ticker:string,position:number,name:string,currency:string}>>;

export function RemoveTicker(arg1:string):Promise<void>;

export function ReorderWatchlist(arg1:Array<string>):Promise<void>;

export function SearchTickers(arg1:string):Promise<Array<{symbol:string,name:string,exchange:string}>>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ValidateTicker(arg1:string):Promise<boolean>;
